from megraph.egraph_constructor import Constructor

egraph_record = '''
SIZE 19
ROOT 16
ECLASS 0
BEGIN_ENODE
BEGIN_SYMBOL x END_SYMBOL
END_ENODE
END_ECLASS
ECLASS 20
BEGIN_ENODE
BEGIN_SYMBOL add END_SYMBOL
BEGIN_CHILDREN 14 15 
END_CHILDREN
END_ENODE
BEGIN_ENODE
BEGIN_SYMBOL reshape END_SYMBOL
BEGIN_CHILDREN 19 13 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 17
BEGIN_ENODE
BEGIN_SYMBOL bias_add END_SYMBOL
BEGIN_CHILDREN 2 7 
END_CHILDREN
END_ENODE
BEGIN_ENODE
BEGIN_SYMBOL flex-linear END_SYMBOL
BEGIN_CHILDREN 0 1 7 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 14
BEGIN_ENODE
BEGIN_SYMBOL reshape END_SYMBOL
BEGIN_CHILDREN 11 13 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 11
BEGIN_ENODE
BEGIN_SYMBOL dense END_SYMBOL
BEGIN_CHILDREN 9 10 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 8
BEGIN_ENODE
BEGIN_SYMBOL add END_SYMBOL
BEGIN_CHILDREN 6 7 
END_CHILDREN
END_ENODE
BEGIN_ENODE
BEGIN_SYMBOL reshape END_SYMBOL
BEGIN_CHILDREN 17 5 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 5
BEGIN_ENODE
BEGIN_SYMBOL shape END_SYMBOL
BEGIN_CHILDREN 3 4 4 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 2
BEGIN_ENODE
BEGIN_SYMBOL dense END_SYMBOL
BEGIN_CHILDREN 0 1 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 19
BEGIN_ENODE
BEGIN_SYMBOL bias_add END_SYMBOL
BEGIN_CHILDREN 11 15 
END_CHILDREN
END_ENODE
BEGIN_ENODE
BEGIN_SYMBOL flex-linear END_SYMBOL
BEGIN_CHILDREN 9 10 15 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 13
BEGIN_ENODE
BEGIN_SYMBOL shape END_SYMBOL
BEGIN_CHILDREN 3 12 12 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 10
BEGIN_ENODE
BEGIN_SYMBOL w2 END_SYMBOL
END_ENODE
END_ECLASS
ECLASS 7
BEGIN_ENODE
BEGIN_SYMBOL b END_SYMBOL
END_ENODE
END_ECLASS
ECLASS 4
BEGIN_ENODE
BEGIN_SYMBOL 4 END_SYMBOL
END_ENODE
END_ECLASS
ECLASS 1
BEGIN_ENODE
BEGIN_SYMBOL w END_SYMBOL
END_ENODE
END_ECLASS
ECLASS 15
BEGIN_ENODE
BEGIN_SYMBOL b2 END_SYMBOL
END_ENODE
END_ECLASS
ECLASS 12
BEGIN_ENODE
BEGIN_SYMBOL 32 END_SYMBOL
END_ENODE
END_ECLASS
ECLASS 9
BEGIN_ENODE
BEGIN_SYMBOL relu END_SYMBOL
BEGIN_CHILDREN 8 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 6
BEGIN_ENODE
BEGIN_SYMBOL reshape END_SYMBOL
BEGIN_CHILDREN 2 5 
END_CHILDREN
END_ENODE
END_ECLASS
ECLASS 3
BEGIN_ENODE
BEGIN_SYMBOL 1 END_SYMBOL
END_ENODE
END_ECLASS

FIN
'''

egraph = Constructor().from_text(egraph_record)
print(egraph)