[package]
name = "flexmatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
serde = "1.0.130"

[dependencies.glenside]
git = "https://github.com/gussmith23/glenside"
branch = "3la-pldi-push-main"
features = ["tvm"]

[dependencies.egg]
git = "https://github.com/AD1024/egg"
branch = "3la-mod"

[dependencies.tvm]
git = "ssh://git@github.com/uwsampl/3la-tvm.git"
rev = "bb6c378e5440899083af253c3466db087157acb6"
